version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container_gameplay
    environment:
      MYSQL_ROOT_PASSWORD: ---
      MYSQL_DATABASE: gameplay
      MYSQL_PASSWORD: ---
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: